import { Award, BookOpen, Brain, Building, Cpu, Eye, FileText, Globe, GraduationCap, Layers, Microscope, Star, Target, User, Users, Zap } from "lucide-react"
import { AwardData, ProfessionalCardData, Skill, Student } from "./Types"

export const socialLinks = [
  { name: "Google Scholar", href: "https://scholar.google.co.in/citations?hl=en&user=8yr9XTAAAAAJ&view_op=list_works", },
  { name: "Scopus", href: "https://www.scopus.com/authid/detail.uri?authorId=57188876957" },
  { name: "ORCID", href: "https://orcid.org/0000-0002-4155-884X" },
  { name: "Web of Science", href: "https://www.webofscience.com/wos/author/record/S-5908-2018" },
  { name: "Research Gate", href: "https://www.researchgate.net/profile/Soumya-Nayak-14" },
  { name: "DBLP", href: "https://dblp.org/pid/250/8949.html" },
  { name: "Vidwan", href: "https://vidwan.inflibnet.ac.in/profile/133065" },
]
export const stats = [
  { icon: FileText, label: "PUBLICATIONS", value: "200+" },
  { icon: Users, label: "SCOPUS INDEX", value: "160+" },
  { icon: Award, label: "SCI/SCIE", value: "60+" },
  { icon: Brain, label: "PATENTS", value: "18+" },
  { icon: BookOpen, label: "BOOKS", value: "8+" }
]
export const researchAreas = [
  {
    icon: Layers,
    title: "FRACTAL GRAPHICS",
    description:
      "Fractal analysis of complex objects in nature, encompassing grayscale and color domains with box-counting techniques.",
  },
  {
    icon: Brain,
    title: "APPLIED AI",
    description:
      "Machine Learning and Deep Learning methodologies applied to biomedical image analysis and pattern recognition.",
  },
  {
    icon: Zap,
    title: "ML/DL",
    description:
      "Advanced machine learning algorithms and deep neural networks for medical imaging and computer vision applications.",
  },
  {
    icon: Microscope,
    title: "BIOMEDICAL IMAGING",
    description:
      "Application of fractal geometry in biomedical image processing with fundamental color image processing techniques.",
  },
  {
    icon: Target,
    title: "PATTERN RECOGNITION",
    description:
      "Character recognition and pattern analysis using fractal dimension as a metric for analyzing self-similar textures.",
  },
  {
    icon: Eye,
    title: "MACHINE VISION",
    description:
      "Computer Vision systems with emphasis on biomedical image analysis and automated diagnostic applications.",
  },
]
export const navigationItems = [
  { name: "HOME", href: "/" },
  { name: "ABOUT ME", href: "/about-me" },
  { name: "EDUCATION", href: "/education" },
  { name: "EXPERIENCE", href: "/experience" },
  {
    name: "WORK",
    dropdown: [
      { name: "RESEARCH INTERESTS", href: "/#research-expertise" },
      { name: "PUBLICATION", href: "/publications" },
      { name: "PROFESSIONAL ACTIVITIES", href: "/professional-activites" },
    ],
  },
  { name: "STUDENTS", href: "/students" },
  { name: "AWARDS & ACHIEVEMENTS", href: "/award-and-achievement" },
  { name: "SKILLS", href: "/skills" },
  { name: "CONTACT", href: "/#contact-us" },
  {
    name: "SOCIAL MEDIA",
    dropdown: [
      { name: "Instagram", href: "https://www.instagram.com/nayak.soumya17/" },
      { name: "Linkedin", href: "https://www.linkedin.com/in/dr-soumya-ranjan-nayak-1ab05715b/" },
      { name: "Facebook", href: "https://www.facebook.com/soumyaranjan.nayak.391" },
      { name: "Twitter", href: "https://x.com/SoumyaR28911292" },
    ],
  },
]
export const educationData = [
  {
    degree: "Ph.D-(CSE/IT)",
    description: "Doctor of Philosophy in Computer Science and Engineering",
    institution: "BPUT (State Govt. Technical University)",
    details: "Under MHRD Govt. of India fellowship-TEQIP-II, Specialization in Fractal (Image Processing)",
    year: "2022",
  },
  {
    degree: "M. Tech-(CSE/IT)",
    description: "Master of Technology in Information Technology",
    institution: "OUTR (formerly CET, State Govt. Technical College under BPUT)",
    details: "Odisha, India",
    year: "2012",
  },
  {
    degree: "B.Tech-(CSE)",
    description: "Bachelor of Technology in Computer Science and Engineering",
    institution: "BPUT, Odisha, India",
    details: "",
    year: "2009",
  },
  {
    degree: "Diploma-(CSE)",
    description: "Diploma in Computer Science and Engineering",
    institution: "SITE under SCTE&VT, Odisha, India",
    details: "",
    year: "2005",
  },
]
export const researchInterests = [
  { name: "Image Processing", icon: Microscope },
  { name: "Pattern Recognition", icon: Target },
  { name: "Computer Vision/Machine Vision", icon: Eye },
  { name: "Fractal Graphics", icon: Layers },
  { name: "Biomedical Imaging", icon: Brain },
]
export const EducationPageeducationData = [
  {
    degree: "Ph.D. in Computer Science and Engineering",
    year: "2022",
    institution: "BPUT (State Govt. Technical University), Odisha, India",
    specialization: "Fractal Image Processing and Pattern Recognition",
    fellowship: "MHRD Govt. of India TEQIP-II",
    thesis: "Analysis of Fractal through their Dimensions",
    icon: Award,
    color: "bg-[#EBB884]",
    textColor: "text-[#1F1F1D]",
  },
  {
    degree: "M.Tech in Information Technology",
    year: "2012",
    institution: "OUTR (formerly CET, under BPUT), Odisha, India",
    icon: GraduationCap,
    color: "bg-[#E8BF96]",
    textColor: "text-[#1F1F1D]",
  },
  {
    degree: "B.Tech in Computer Science and Engineering",
    year: "2009",
    institution: "BPUT, Odisha, India",
    icon: Cpu,
    color: "bg-[#FCF0F0]",
    textColor: "text-[#1F1F1D]",
    border: "border-2 border-[#EBB884]",
  },
  {
    degree: "Diploma in Computer Science and Engineering",
    year: "2005",
    institution: "SITE, under SCTE&VT, Odisha, India",
    icon: BookOpen,
    color: "bg-[#2A2A28]",
    textColor: "text-[#EBB884]",
  },
]
export const experiences = [
  {
    icon: GraduationCap,
    title: "Assistant Professor",
    organization: "School of Computer Engineering, KIIT University",
    location: "Bhubaneswar, India",
    duration: "Nov 2022 – Present",
    responsibilities: [
      "Teaching undergraduate and postgraduate courses in Computer Science & AI",
      "Published 50+ research articles, 4 patents, 2 books, and 1 copyright",
      "Guiding Ph.D. and M.Tech research scholars",
      "Actively engaged in funded research and patents",
      "Contributed to departmental curriculum design and academic growth",
    ],
  },
  {
    icon: Building,
    title: "Assistant Professor",
    organization: "Amity School of Engineering and Technology, Amity University",
    location: "Noida, India",
    duration: "Feb 2020 – Nov 2022 (2.10 yrs)",
    responsibilities: [
      "Teaching undergraduate and postgraduate courses in Computer Science & Engineering",
      "Supervised M.Tech students in AI/ML",
      "Worked on research publications in collaboration with international universities and scholars",
      "Engaged in cross-border academic collaborations leading to peer-reviewed journal papers",
      "Contributed to the design and enhancement of departmental curriculum, ensuring alignment with industry and research trends",
    ],
  },
  {
    icon: Users,
    title: "Assistant Professor",
    organization: "Chitkara University of Research and Innovation Network (CURIN), Chitkara University",
    location: "Punjab, India",
    duration: "Apr 2019 – Jan 2020 (10 months)",
    responsibilities: [
      "Delivered lectures in Data Science and Computer Vision",
      "Engaged in collaborative academic research, resulting in multiple peer-reviewed publications",
      "Played a key role in curriculum development and academic quality improvement initiatives",
      "Contributed to externally funded research initiatives and secured intellectual property (patents)",
    ],
  },
  {
    icon: BookOpen,
    title: "Assistant Professor",
    organization: "Department of Computer Science and Engineering, K L University",
    location: "Andhra Pradesh, India",
    duration: "Jul 2017 – Apr 2019 (1.10 yrs)",
    responsibilities: [
      "Delivered lectures and tutorials for UG and PG programs, focusing on AI, ML, and Data Science",
      "Actively involved in curriculum design, program structuring, and fostering academic growth of the department",
      "Guided student projects in AI & Machine Learning",
      "Actively contributed to joint research publications in reputed journals and conferences",
      "Participated in academic committees",
    ],
  },
  {
    icon: Award,
    title: "Research Scholar",
    organization: "Department of Information Technology, College of Engineering and Technology",
    location: "India",
    duration: "Dec 2013 – Mar 2017 (3.04 yrs)",
    responsibilities: [
      "Conducted Ph.D. research in Computer Vision & AI",
      "Published in reputed international journals",
    ],
  },
  {
    icon: GraduationCap,
    title: "Sr. Lecturer",
    organization: "Department of Computer Science and Engineering, Vivekananda Institute of Technology",
    location: "Odisha, India",
    duration: "Aug 2012 – Dec 2013 (1.05 yrs)",
    responsibilities: ["Taught undergraduate courses in programming & software engineering"],
  },
]

export const journalPublications = [
  {
    id: 1,
    title: "Performance Evaluation of IPE and IE-Affected Patients using a Modified PSO and ANFIS",
    authors: "S.R. Nayak, K. Swain, T. K. Tak, K. Upreti, P. R. Kshirsagar, S. B. Krishnan, R. C. Poonia, and S. K. Mohapatra",
    journal: "Journal of Mechanics of Continua and Mathematical Sciences",
    volume: "20 (6)",
    pages: "65-89",
    year: 2025,
    type: "SCOPUS",
    category: "journal",
  },
  {
    id: 2,
    title: "Internet of Medical Things-enabled Brain Tumor Classification Using GWO-based Optimized RBF Network",
    authors: "S.K. Panda, R.C. Barik, S.R. Nayak, and G. Panda",
    journal: "Journal of Electronic Imaging",
    volume: "33 (6)",
    pages: "063046-063046",
    year: 2024,
    type: "SCI",
    category: "journal",
  },
  {
    id: 3,
    title: "BT-CNN: A Balanced Binary Tree Architecture for Classification of Brain Tumour Using MRI Imaging",
    authors: "S. Chauhan, R. Cheruku, D.R. Edla, K. Lavanya, S.R. Nayak, J. Giri, S. Mallik, S. Aluvala, V. Boddu, and H. Qin",
    journal: "Frontiers in Physiology",
    volume: "15",
    pages: "1349111",
    year: 2024,
    type: "SCIE",
    category: "journal",
  },
  {
    id: 4,
    title: "Reconfigurable Neuromorphic Neural Network Architecture",
    authors: "K. Sharma, P.K. Sarangi, P. Sharma, S.R. Nayak, S. Aluvala, and S.K. Swain",
    journal: "Applied Computational Intelligence and Soft Computing",
    volume: "24",
    pages: "6632801",
    year: 2024,
    type: "ESCI",
    category: "journal",
  },
  {
    id: 5,
    title: "Leveraging Ensemble Learning for Enhanced Security in Credit Card Transaction Fraudulent within Smart Cities for Cybersecurity Challenges",
    authors: "B. Padhi, S. Chakravarty, B. Naik, S.R. Nayak, and R.C. Poonia",
    journal: "Journal of Discrete Mathematical Sciences and Cryptography",
    volume: "27 (4)",
    pages: "1233-1246",
    year: 2024,
    type: "ESCI",
    category: "journal",
  },
  {
    id: 6,
    title: "Detection of COVID-19 using edge devices by a light-weight convolutional neural network from chest X-ray images",
    authors: "S. Chauhan, D. Reddy, V.R. Cheruku, S.R. Nayak",
    journal: "BMC Medical Imaging",
    volume: "24 (1)",
    pages: "1-15",
    year: 2024,
    type: "SCI",
    category: "journal",
  },
  {
    id: 7,
    title: "DMF-Net: a deep multi-level semantic fusion network for high-resolution chest CT and X-ray image de-noising",
    authors: "T.K. Nayak, C.S. Rao, S.R. Nayak, B.M. Gedefaw",
    journal: "BMC Medical Imaging",
    volume: "23",
    pages: "1-15",
    year: 2024,
    type: "SCI",
    category: "journal",
  },
  {
    id: 8,
    title: "A new efficient referential genome compression technique for FastQ files",
    authors: "S. Kumar, M.K. Singh, S.R. Nayak, A.U. Khan, A.k. Jain",
    journal: "Functional & Integrative Genomics",
    volume: "23",
    pages: "1-15",
    year: 2024,
    type: "SCI",
    category: "journal",
  },
  {
    id: 9,
    title: "DELM: Deep Ensemble Learning Model for Multiclass Classification of Super-Resolution Leaf Disease Images",
    authors: "P. Kaur, M.K. Singh, A.M. Mishra, A. Shankar, P. Singh, M. Diwakar, S.R. Nayak",
    journal: "Turkish Journal of Agriculture and Forestry",
    volume: "47 (5)",
    pages: "1-21",
    year: 2024,
    type: "SCI",
    category: "journal",
  },
  {
    id: 10,
    title: "Towards Early Intervention: Detecting Parkinson's Disease through Voice Analysis with Machine Learning",
    authors: "K.P. Swain, S.R. Samal, V. Ravi, S.R. Nayak, T.J. Alahmadi, P. Singh, and M. Diwakar",
    journal: "The Open Biomedical Engineering Journal",
    volume: "18",
    pages: "1-10",
    year: 2024,
    type: "SCOPUS",
    category: "journal",
  },
  {
    id: 11,
    title: "Leveraging Machine Learning and Patient Reviews for Developing a Drug Recommendation System to Reduce Medical Errors",
    authors: "K.P. Swain, S.K. Mohapatra, V. Ravi, S.R. Nayak, T.J. Alahmadi, P. Singh, and M. Diwakar",
    journal: "The Open Bioinformatics Journal",
    volume: "17",
    pages: "1-10",
    year: 2024,
    type: "SCOPUS",
    category: "journal",
  },
  {
    id: 12,
    title: "A New-fangled Classification Algorithm for Medical Heart Diseases Analysis Using Wavelet Transforms",
    authors: "S.R. Nayak, S. Selvarasu, B. Sripathy, P. Singh, M. Diwakar, I. Gupta, V. Ravi, and A.A. Mazroa",
    journal: "The Open Public Health Journal",
    volume: "17",
    pages: "1-10",
    year: 2024,
    type: "SCOPUS",
    category: "journal",
  },
  {
    id: 13,
    title: "Empowering Crop Selection with Ensemble Learning and K-means Clustering: A Modern Agricultural Perspective",
    authors: "K.P. Swain, S.R. Nayak, V. Ravi, S. Mishra, T.J. Alahmadi, P. Singh, and M. Diwakar",
    journal: "The Open Agriculture Journal",
    volume: "18",
    pages: "1-10",
    year: 2024,
    type: "SCOPUS",
    category: "journal",
  },
  {
    id: 14,
    title: "DELM: Deep Ensemble Learning Model for Multiclass Classification of Super-Resolution Leaf Disease Images",
    authors: "K.K. Jena, S.K. Bhoi, S.R. Nayak, R. Panigrahi, A.K. Bhoi",
    journal: "IEEE Big Data Mining and Analytics",
    volume: "6 (1)",
    pages: "32-43",
    year: 2023,
    type: "SCI",
    category: "journal",
  },
  {
    id: 15,
    title: "Enhanced Framework for COVID-19 Prediction with Computed Thermography Scan Images using Dense Convolution Neural Network and Loss Function",
    authors: "A. Motwani, P. K Shukla, M. Pawar, M. Kumar, U. Ghosh, W. Alnumay, S.R. Nayak",
    journal: "Computer and Electrical Engineering",
    volume: "105",
    pages: "108479",
    year: 2023,
    type: "SCI",
    category: "journal",
  },
  {
    id: 16,
    title: "An Efficient Deep Learning Method for detection of COVID-19 Infection Using Chest X-Ray Images",
    authors: "S.R. Nayak, D.R. Nayak, U. Sinha, V. Arora, R. Pachuri",
    journal: "Diagnostics",
    volume: "13",
    pages: "",
    year: 2023,
    type: "SCI",
    category: "journal",
  },
  {
    id: 17,
    title: "Classification of brain Tumours in MRI images using a convolution neural network",
    authors: "I. Gupta, S. Singh, S. Gupta, S.R. Nayak",
    journal: "Diagnostics",
    volume: "20",
    pages: "",
    year: 2023,
    type: "SCIE",
    category: "journal",
  },
  {
    id: 18,
    title: "An Automated Light Weight Deep Neural Network for Diagnosis of COVID-19 from Chest X-ray Images",
    authors: "S.R. Nayak, J. Nayak, V. Arora, U. Sinha, U. Ghosh",
    journal: "Arabian Journal for Science and Engineering",
    volume: "48",
    pages: "11085-11102",
    year: 2023,
    type: "SCI",
    category: "journal",
  },
  {
    id: 19,
    title: "Automated Detection and Segmentation of exudates for the screening background retinopathy",
    authors: "J.Kaur, D. Mittal, S.Malebary, S.R. Nayak, D. Kumar, M. Kumar, S. Singh",
    journal: "Journal of Healthcare Engineering",
    volume: "Article ID-4537253",
    pages: "1-12",
    year: 2022,
    type: "SCI",
    category: "journal",
  },
  {
    id: 20,
    title: "Intrusion Detection in Cyber-Physical Environment Using Hybrid Naïve Bayes - Decision Table and Multi-Objective Evolutionary Feature Selection",
    authors: "R.Panigrahi, S. Borah, M. Pramanik, A.K.Bhoi, P. Barsocchi, S.R. Nayak, W. Alnumay",
    journal: "Computer Communication",
    volume: "188",
    pages: "133-144",
    year: 2022,
    type: "SCI",
    category: "journal",
  },
  {
    id: 21,
    title: "Central hubs prediction for Bio Networks by Directed Hypergraph - GA with validation to COVID-19 PPI",
    authors: "S. Gopalakrishnan, S. Sridharan, S.R. Nayak, J. Nayak, S. Venkataraman",
    journal: "Pattern Recognition Letter",
    volume: "153",
    pages: "246-253",
    year: 2022,
    type: "SCI",
    category: "journal",
  },
  {
    id: 22,
    title: "Enhanced Framework for COVID-19 prediction with Computed Tomography scan Images using Dense-CNN and novel Loss Function",
    authors: "A. Motwani, P. Shukla, M. Pawar, M. Kumar, U. Ghosh, W. Numay, S.R. Nayak",
    journal: "Computer and Electrical Engineering",
    volume: "105",
    pages: "108479",
    year: 2022,
    type: "SCI",
    category: "journal",
  },
  {
    id: 23,
    title: "Modified U-NET Architecture for Segmentation of Skin Lesion",
    authors: "V. Anand, S. Gupta, D. Koundal, S.R. Nayak, P. Barsocchi, A.K.Bhoi",
    journal: "Sensors",
    volume: "22",
    pages: "1-21",
    year: 2022,
    type: "SCI",
    category: "journal",
  },
  {
    id: 24,
    title: "An Automated Deep Learning Models for Classification of Skin Disease using Dermoscopy Images: A Comprehensive Study",
    authors: "V. Anand, S. Gupta, S.R. Nayak, D. Koundal, D.Prakash, K.D. Varma",
    journal: "Multimedia Tools and Applications",
    volume: "81",
    pages: "37379-37401",
    year: 2022,
    type: "SCI",
    category: "journal",
  },
  {
    id: 25,
    title: "A Deep Learning Based approach to Detect IDC in Histopathology Images",
    authors: "I. Gupta, S.R. Nayak, S. Gupta, S. Singh, K.D. Verma, A. Gupta, D. Prakash",
    journal: "Multimedia Tools and Applications",
    volume: "81",
    pages: "36309-36330",
    year: 2022,
    type: "SCI",
    category: "journal",
  },
  {
    id: 26,
    title: "A Novel Service Robot Assignment Approach for COVID-19 Infected Patients: A Case of Medical Data Driven Decision Making",
    authors: "K.K. Jena, S.R. Nayak, S. Bhoi, D. Prakash, K.D. Varma",
    journal: "Multimedia Tools and Applications",
    volume: "81 (29)",
    pages: "41995-42021",
    year: 2022,
    type: "SCI",
    category: "journal",
  },
  {
    id: 27,
    title: "An enhanced Transfer Learning based Classification for Diagnosis of Skin Cancer",
    authors: "V. Anand, S. Gupta, A. Altameen, S.R. Nayak, A.K.J. Saudagar, R.C. Poonia",
    journal: "Diagnostics",
    volume: "12 (7)",
    pages: "1-18",
    year: 2022,
    type: "SCI",
    category: "journal",
  },
  {
    id: 28,
    title: "HTLML: Hybrid AI Based Model for Detection of Alzheimer's Disease",
    authors: "S. Sharma, S. Gupta, D. Gupta, A. Altameem, A.K.J. Saudagar, R.C. Poonia, S.R. Nayak",
    journal: "Diagnostics",
    volume: "12 (8)",
    pages: "1833",
    year: 2022,
    type: "SCI",
    category: "journal",
  },
  {
    id: 29,
    title: "MeQryEP: A Texture based Descriptor for Biomedical Image Retrieval",
    authors: "G. Deep, J. Kaur, S.P. Singh, S.R. Nayak, M. Kumar, S. Kautish",
    journal: "Journal of Healthcare Engineering",
    volume: "Article ID-9505229",
    pages: "1-20",
    year: 2022,
    type: "SCI",
    category: "journal",
  },
  {
    id: 30,
    title: "Stacked Ensemble of fine-tuned Transfer Learning Models to Predict Protein Subcellular Localization using Confocal Microscopy",
    authors: "S. Agrawal, S. Gupta, R.C. Poonia, A. Altameem, S.R. Nayak, A.K.J. Saudagar, R. Ahuja",
    journal: "Computational Intelligence and Neuroscience",
    volume: "",
    pages: "",
    year: 2022,
    type: "SCI",
    category: "journal",
  },
  {
    id: 31,
    title: "GaitRec-Net: A Deep Neural Network for Gait Disorder Detection using Ground Reaction Force",
    authors: "C. Pandey, D.S. Roy, R.C. Poonia, A.Altameem, S.R. Nayak, A. Verma, A.K.J. Saudagar",
    journal: "PPAR Research",
    volume: "Article ID-9355015",
    pages: "1-10",
    year: 2022,
    type: "SCI",
    category: "journal",
  },
  {
    id: 32,
    title: "Analysis of Noise Pollution during Dussehra Festival in Bhubaneswar Smart City in India: A Study using Machine Learning Models",
    authors: "S.K. Bhoi, C. Mallik, C.R. Mohanty, S.R. Nayak",
    journal: "Applied Computational Intelligence and Soft Computing",
    volume: "Article ID-6095265",
    pages: "1-10",
    year: 2022,
    type: "ESCI",
    category: "journal",
  },
  {
    id: 33,
    title: "Evaluating the Usability of mHealth Applications on Type-2 Diabetes Mellitus using various MCDM Models",
    authors: "Kamaldeep, S. Roy, R.C. Poonia, S.R. Nayak, R. Kumar, K.J. Alzahrani, M.M. Alnfiai, F.N.A. Wesabi",
    journal: "Healthcare",
    volume: "10(1):4",
    pages: "1-29",
    year: 2022,
    type: "SCI",
    category: "journal",
  },
  {
    id: 34,
    title: "Design of Smart and Secured Healthcare Service using Deep Learning with Modified SHA-256 Algorithm",
    authors: "M.D. Mohanty, A. Das, M.N Mohanty, A. Altameem, S.R. Nayak, A.K.J. Saudagar, R.C. Poonia",
    journal: "Healthcare",
    volume: "10, 7",
    pages: "1275",
    year: 2022,
    type: "SCI",
    category: "journal",
  },
  {
    id: 35,
    title: "Multi-Criteria Usability Evaluation of mHealth Applications on Type 2 Diabetes Mellitus using Hybrid MCDM Models of CODAS-FAHP and MOORA-FAHP",
    authors: "K. Gupta, S. Roy, R.C. Poonia, R. Kumar, S.R. Nayak, A. Altameem, A.K.J. Saudagar",
    journal: "Applied Sciences",
    volume: "12 (9)",
    pages: "4156",
    year: 2022,
    type: "SCI",
    category: "journal",
  },
  {
    id: 36,
    title: "A Blockchain Security Scheme to support Fog-Based Internet of Things",
    authors: "D. Mohapatra. S.K. Bhoi, K.K. Jena, S.R. Nayak, A. Singh",
    journal: "Microprocessors and Microsystems",
    volume: "89",
    pages: "104455",
    year: 2022,
    type: "SCI",
    category: "journal",
  },
  {
    id: 37,
    title: "Integrated Industrial Reference Architecture for Smart Healthcare in Internet of Things: A Systematic Investigation",
    authors: "A.D. Aguru, E.S. Suresh Babu, S.R. Nayak, A. Sethy, A. Verma",
    journal: "Algorithms",
    volume: "15 (9)",
    pages: "1-38",
    year: 2022,
    type: "ESCI",
    category: "journal",
  },
  {
    id: 38,
    title: "A Hybrid System for Handwritten Character Recognition with High Robustness",
    authors: "A. Sethy, P.K. Patra, S.R. Nayak",
    journal: "Traitement du Signal",
    volume: "39(2)",
    pages: "567-576",
    year: 2022,
    type: "SCI",
    category: "journal",
  },
  {
    id: 39,
    title: "Multi-Class Skin Disease Classification using Transfer Learning Model",
    authors: "V. Anand, S. Gupta, D. Koundal, S.R. Nayak, J. Nayak",
    journal: "International Journal on Artificial Intelligence Tools",
    volume: "31 (02)",
    pages: "",
    year: 2022,
    type: "SCI",
    category: "journal",
  },
  {
    id: 40,
    title: "Offline Signature Verification using Deep Neural Network with Application to Computer Vision",
    authors: "N. Sharma, S. Gupta, P. Mehta, S.R. Nayak, X. Cheng, A. Shankar, P. Singh",
    journal: "Journal of Electronic Imaging",
    volume: "31 (4)",
    pages: "0410210-1-18",
    year: 2022,
    type: "SCI",
    category: "journal",
  },
  {
    id: 41,
    title: "Generation of cantor sets from fractal squares: A mathematical prospective",
    authors: "S.K. Das, S.R. Nayak, J. Mishra",
    journal: "Journal of Interdisciplinary Mathematics",
    volume: "25(3)",
    pages: "863-880",
    year: 2022,
    type: "ESCI",
    category: "journal",
  },
  {
    id: 42,
    title: "A mathematical model for generation of interactive fractals using a fourth order fractal square: A case study",
    authors: "S.K. Das, S.R. Nayak, J. Mishra",
    journal: "Journal of Interdisciplinary Mathematics",
    volume: "25(7)",
    pages: "1979-1988",
    year: 2022,
    type: "ESCI",
    category: "journal",
  },
  {
    id: 43,
    title: "License Plate Recognition Using Neural Architecture Search for Edge Devices",
    authors: "J. Shashirangana, H. Padmasiri, D. Meedeniya, C. Perera, S.R. Nayak, J. Nayak, S. Vimal, S. Kadry",
    journal: "International Journal of Intelligent Systems",
    volume: "",
    pages: "",
    year: 2021,
    type: "SCI",
    category: "journal",
  },
  {
    id: 44,
    title: "Offline Signature Verification Using Elementary Combinations of Directional Codes from Boundary Pixels",
    authors: "M.A.S. Pratihar, S.R. Nayak, T. Hanne, D.S. Roy",
    journal: "Neural Computing and Applications",
    volume: "",
    pages: "",
    year: 2021,
    type: "SCI",
    category: "journal",
  },
  {
    id: 45,
    title: "Application of Deep Learning techniques for Detection of COVID-19 Cases using Chest X-ray Images: A Comprehensive Study",
    authors: "S.R. Nayak, D.R. Nayak, V. Arora, U. Sinha, R.B. Pachuri",
    journal: "Biomedical Signal Processing and Control",
    volume: "64",
    pages: "102365",
    year: 2021,
    type: "SCI",
    category: "journal",
  },
  {
    id: 46,
    title: "Fractal Dimension based Generalised Box-Counting Technique with Application to Gray Scale Images",
    authors: "S.R. Nayak, J. Mishra",
    journal: "Fractals",
    volume: "29 (3)",
    pages: "2150055",
    year: 2021,
    type: "SCI",
    category: "journal",
  },
  {
    id: 47,
    title: "Amalgamation of Customer Relationship Management and Data Analytics in different business sectors-A Systematic Literature Review",
    authors: "Saha, H.K. Tripathy, S.R. Nayak, A.K. Bhoi, P.L. Barsocchi",
    journal: "Sustainability",
    volume: "13(9)",
    pages: "5279",
    year: 2021,
    type: "SCI",
    category: "journal",
  },
  {
    id: 48,
    title: "An Ensemble AI-Enabled MIoT for Automated Diagnosis of Malaria Parasite",
    authors: "S.R. Nayak, J. Nayak, S. Vimal, V. Arora, U. Sinha",
    journal: "Expert Systems",
    volume: "39 (4)",
    pages: "1-15",
    year: 2021,
    type: "SCI",
    category: "journal",
  },
  {
    id: 49,
    title: "Modified Pixel Level Snake using Bottom Hat Transformation for Evolution of Retinal Vasculature Map",
    authors: "M. Garg, S. Gupta, S.R. Nayak, J. Nayak, D. Pelusi",
    journal: "Mathematical Biosciences and Engineering",
    volume: "18(5)",
    pages: "5737-5757",
    year: 2021,
    type: "SCI",
    category: "journal",
  },
  {
    id: 50,
    title: "UAVs Path Planning Architecture for Effective Medical Emergency Response in Future Networks",
    authors: "S.I. Khan, Z. Qadir, H.S. Munawar, S.R. Nayak, K.D. Verma, D. Prakash",
    journal: "Physical Communication",
    volume: "47",
    pages: "101337",
    year: 2021,
    type: "SCI",
    category: "journal",
  },
  {
    id: 51,
    title: "Ensemble-Based Machine Learning for Predicting Sudden Human Fall Using Health Data, Mathematical Problems in Engineering",
    authors: "U. Saxena, S. Moulik, S.R. Nayak, T. Hanne, D.S. Roy",
    journal: "Mathematical Problems in Engineering",
    volume: "2021",
    pages: "8608630",
    year: 2021,
    type: "SCI",
    category: "journal",
  },
  {
    id: 52,
    title: "Directive Clustering Contrast based Multi-Modality Medical Image Fusion for Smart Healthcare System",
    authors: "M. Diwakar, P. Singh, A. Shankar, S.R. Nayak, J. Nayak, S. Vimal, R. Singh, D. Sisodia",
    journal: "Network Modeling Analysis in Health Informatics and Bioinformatics",
    volume: "11 (15)",
    pages: "",
    year: 2021,
    type: "SCOPUS",
    category: "journal",
  },
  {
    id: 53,
    title: "Offline Handwritten Character Recognition: A Kernel Based Approach",
    authors: "A. Sethy, S.R. Nayak, P.K. Patra, R.C. Poonia",
    journal: "Journal of Social Ecology and Sustainable Development",
    volume: "13 (1)",
    pages: "1-14",
    year: 2021,
    type: "SCOPUS",
    category: "journal",
  },
  {
    id: 54,
    title: "Detection of Bifurcations and Crossovers Points from Retinal Vasculature Map using Modified Windows Feature-Point Detection (MWFD) Approach",
    authors: "M. Garg, S. Gupta, S.R. Nayak",
    journal: "International Journal of Computer Applications in Technology",
    volume: "64 (4)",
    pages: "361-374",
    year: 2021,
    type: "SCOPUS",
    category: "journal",
  },
  {
    id: 55,
    title: "MED-NET : A Novel Approach to ECG Anomaly Detection Using LSTM Autoencoders",
    authors: "K. Dutta, R. Lenka, S.R. Nayak, A. Khandual, A.K. Bhoi",
    journal: "International Journal of Computer Applications in Technology",
    volume: "65 (4)",
    pages: "343-357",
    year: 2021,
    type: "SCOPUS",
    category: "journal",
  },
  {
    id: 56,
    title: "Machine Learning Based classification: An Analysis Based on COVID-19 Transmission Electron Microscopy Images",
    authors: "K.K. Jena, S.K. Bhoi, S.R. Nayak, C.R. Pattanaik",
    journal: "International Journal of Computer Applications in Technology",
    volume: "66 (3-4)",
    pages: "350-361",
    year: 2021,
    type: "SCOPUS",
    category: "journal",
  },
  {
    id: 57,
    title: "Edge and Region Segmentation in High-Resolution Aerial Images using Improved Kernel Density Estimation: A Hybrid Approach",
    authors: "M. Marveal, S.R. Nayak",
    journal: "Journal of Intelligent and Fuzzy Systems",
    volume: "39",
    pages: "543-560",
    year: 2020,
    type: "SCI",
    category: "journal",
  },
 {
    id: 58,
    title: "Generation of cantor sets from fractal squares: A mathematical prospective",
    authors: "S.K. Das, S.R. Nayak, J. Mishra",
    journal: "Journal of Interdisciplinary Mathematics",
    volume: "25 (3)",
    pages: "863-880",
    year: 2022,
    type: "ESCI",
    category: "journal",
  },
  {
    id: 59,
    title: "A mathematical model for generation of interactive fractals using a fourth order fractal square: A case study",
    authors: "S.K. Das, S.R. Nayak, J. Mishra",
    journal: "Journal of Interdisciplinary Mathematics",
    volume: "25 (7)",
    pages: "1979-1988",
    year: 2022,
    type: "ESCI",
    category: "journal",
  },
  {
    id: 60,
    title: "Biomedical signal to image conversion and classification using flexible deep learning techniques",
    authors: "A. Das, S.R. Nayak, M. Mohanty, P.K. Shukla",
    journal: "Int. J. Business Intelligence and Data Mining",
    volume: "24 (2)",
    pages: "183-202",
    year: 2022,
    type: "SCOPUS",
    category: "journal",
  },
  {
    id: 61,
    title: "Monitoring the land use, Land cover change of Roorkee region change (Uttarkhand, India) Using Machine Learning Techniques",
    authors: "A. Kumar, R.D. Garg, P. Singh, A. Shankar, S.R. Nayak, M. Diwakar",
    journal: "International Journal of Social Ecology and Sustainable Development",
    volume: "14 (1)",
    pages: "1-16",
    year: 2023,
    type: "SCOPUS",
    category: "journal",
  },
  {
    id: 62,
    title: "Directive Clustering Contrast based Multi-Modality Medical Image Fusion for Smart Healthcare System",
    authors: "M. Diwakar, P. Singh, A. Shankar, S.R. Nayak, J. Nayak, S. Vimal, R. Singh, D. Sisodia",
    journal: "Network Modeling Analysis in Health Informatics and Bioinformatics",
    volume: "11 (15)",
    pages: "",
    year: 2021,
    type: "SCOPUS",
    category: "journal",
  },
  {
    id: 63,
    title: "Offline Handwritten Character Recognition: A Kernel Based Approach",
    authors: "A. Sethy, S.R. Nayak, P.K. Patra, R.C. Poonia",
    journal: "Journal of Social Ecology and Sustainable Development",
    volume: "13 (1)",
    pages: "1-14",
    year: 2021,
    type: "SCOPUS",
    category: "journal",
  },
  {
    id: 64,
    title: "Detection of Bifurcations and Crossovers Points from Retinal Vasculature Map using Modified Windows Feature-Point Detection (MWFD) Approach",
    authors: "M. Garg, S. Gupta, S.R. Nayak",
    journal: "International Journal of Computer Applications in Technology",
    volume: "64 (4)",
    pages: "361-374",
    year: 2021,
    type: "SCOPUS",
    category: "journal",
  },
  {
    id: 65,
    title: "MED-NET : A Novel Approach to ECG Anomaly Detection Using LSTM Autoencoders",
    authors: "K. Dutta, R. Lenka, S.R. Nayak, A. Khandual, A.K. Bhoi",
    journal: "International Journal of Computer Applications in Technology",
    volume: "65 (4)",
    pages: "343-357",
    year: 2021,
    type: "SCOPUS",
    category: "journal",
  },
  {
    id: 66,
    title: "Machine Learning Based classification: An Analysis Based on COVID-19 Transmission Electron Microscopy Images",
    authors: "K.K. Jena, S.K. Bhoi, S.R. Nayak, C.R. Pattanaik",
    journal: "International Journal of Computer Applications in Technology",
    volume: "66 (3-4)",
    pages: "350-361",
    year: 2021,
    type: "SCOPUS",
    category: "journal",
  },
  {
    id: 67,
    title: "A Statistical Analysis of COVID-19 using Gaussian Probabilistic Model",
    authors: "S.R. Nayak, V. Arora, U. Sinha, R.C. Poonia",
    journal: "Journal of Interdisciplinary Mathematics",
    volume: "24 (1)",
    pages: "19-32",
    year: 2020,
    type: "ESCI",
    category: "journal",
  },
  {
    id: 68,
    title: "Suicidal Ideation Prediction in Twitter Data using Machine Learning Techniques",
    authors: "E.R. Kumar, K.V.S.N. Ramarao, S.R. Nayak",
    journal: "Journal of Interdisciplinary Mathematics",
    volume: "23 (1)",
    pages: "117-125",
    year: 2020,
    type: "ESCI",
    category: "journal",
  },
  {
    id: 69,
    title: "Fuzzy Rule Based Intelligent System for User Authentication Based on User Behaviour",
    authors: "A. Roy, N. Parveen, S. Razia, S.R. Nayak, R.C. Poonia",
    journal: "Journal of Discrete Mathematical Sciences & Cryptography",
    volume: "23 (2)",
    pages: "409-417",
    year: 2020,
    type: "ESCI",
    category: "journal",
  },
  {
    id: 70,
    title: "MRI Brain Tumor Analysis using Fuzzy Rule Based Approach",
    authors: "K.K. Jena, S. Mishra, S. Mishra, S. Bhoi, S.R. Nayak",
    journal: "Journal of Research on the Lepidoptera",
    volume: "50 (2)",
    pages: "98-112",
    year: 2019,
    type: "SCOPUS",
    category: "journal",
  },
  {
    id: 71,
    title: "A Modified Triangle Box-Counting with precision in Error fit",
    authors: "S.R. Nayak, J. Mishra",
    journal: "Journal of Information and Optimization Sciences",
    volume: "39 (1)",
    pages: "113-128",
    year: 2018,
    type: "ESCI",
    category: "journal",
  },
  {
    id: 72,
    title: "Fractal Analysis of Image sets using Differential Box Counting Techniques",
    authors: "S.R. Nayak, P.M. Jena, J. Mishra",
    journal: "International Journal of Information Technology",
    volume: "10 (1)",
    pages: "39-47",
    year: 2018,
    type: "SCOPUS",
    category: "journal",
  },
  {
    id: 73,
    title: "Ripplet Transformation Based Off-line Handwritten Character & Numeral Recognition",
    authors: "A. Sethy, P.K. Patra, S.R. Nayak",
    journal: "Journal of Advanced Research in Dynamical and Control Systems",
    volume: "10 (5)",
    pages: "31-39",
    year: 2018,
    type: "SCOPUS",
    category: "journal",
  },
  {
    id: 74,
    title: "A Gabor Wavelet Based Approach for Off-Line Recognition of Odia Handwritten Numerals",
    authors: "A. Sethy, P.K. Patra, S.R. Nayak, D.R. Nayak",
    journal: "International Journal of Engineering and Technology (UAE)",
    volume: "07 (2.32)",
    pages: "253-257",
    year: 2018,
    type: "SCOPUS",
    category: "journal",
  },
  {
    id: 75,
    title: "Fractal Geometry: The Beauty of Computer Graphics",
    authors: "S.K. Das, S.R. Nayak, J. Mishra",
    journal: "Journal of Advanced Research in Dynamical and Control Systems",
    volume: "9 (10)",
    pages: "76-82",
    year: 2017,
    type: "SCOPUS",
    category: "journal",
  },
  {
    id: 76,
    title: "An improved method to estimate the fractal dimension of colour images",
    authors: "S.R. Nayak, J. Mishra",
    journal: "Perspectives in Science",
    volume: "08",
    pages: "412-416",
    year: 2016,
    type: "SCOPUS",
    category: "journal",
  }
]
export const conferencePublications = [
  {
    id: 1,
    title:
      "Automated Brain Tumor Detection in MRI Images using YOLOv8: A Real-Time Diagnosis Tool for Precision Oncology",
    authors: "K. P. Swain, S. R. Nayak, S. K. Swain, and S. K. Mohapatra",
    conference: "Advances in Intelligent Computing and Communication: Proceedings of ICAC 2024",
    volume: "1325",
    pages: "13",
    year: 2025,
    type: "Springer (Scopus)",
    category: "conference",
  },
  {
    id: 2,
    title: "Vision Transformer-Based Automated Classification of Acute Lymphoblastic Leukemia",
    authors: "K. P. Swain, S. K. Swain, and S. R. Nayak",
    conference: "International Conference on Emerging Systems and Intelligent Computing (ESIC)",
    volume: "",
    pages: "584–588",
    year: 2025,
    type: "IEEE (Scopus)",
    category: "conference",
  },
  {
    id: 3,
    title:
      "Employing sequence-to-sequence stacked LSTM autoencoder architecture to forecast Indian weather",
    authors: "A. Maharatha, R. Das, J. Mishra, S.R. Nayak, and S. Aluvala",
    conference: "Procedia Computer Science",
    volume: "235",
    pages: "2258–2268",
    year: 2024,
    type: "Elsevier (Scopus)",
    category: "conference",
  },
  {
    id: 4,
    title:
      "Computer Vision-Based Smart Helmet with Voice Assistant for Increasing Driver Safety",
    authors: "Y. Grover, S.G. Mishra, S. Kumar, S.R. Nayak",
    conference:
      "Advances and Applications of Artificial Intelligence & Machine Learning: Proceedings of ICAAAIML",
    volume: "1078",
    pages: "203–216",
    year: 2023,
    type: "Springer (Scopus)",
    category: "conference",
  },
  {
    id: 5,
    title: "Time Series Analysis of Cryptocurrency using ARIMAX",
    authors: "S. Sejwal, K. Aggarwal, S.R. Nayak",
    conference:
      "Advances and Applications of Artificial Intelligence & Machine Learning: Proceedings of ICAAAIML",
    volume: "1078",
    pages: "233–245",
    year: 2023,
    type: "Springer (Scopus)",
    category: "conference",
  },
  {
    id: 6,
    title:
      "Time Series Analysis of Cryptocurrency: Factors and its Prospectives",
    authors: "S. Sejwal, K. Agarwal, S.R. Nayak, J.B. Awotunde",
    conference: "Advances in Communication, Devices and Networking (ICCDN)",
    volume: "902",
    pages: "251–263",
    year: 2022,
    type: "Springer LNEE",
    category: "conference",
  },
  {
    id: 7,
    title:
      "A Review on Internet of Things: Communication Protocols, Wireless Technologies, and Applications",
    authors:
      "M. Garg, G. Kaur, G. Singh, G. Sandhu, S. Gupta, S.R. Nayak, M.F. Ijaz",
    conference: "Advances in Communication, Devices and Networking (ICCDN)",
    volume: "902",
    pages: "265–278",
    year: 2022,
    type: "Springer LNEE",
    category: "conference",
  },
  {
    id: 8,
    title:
      "Online Affinity of Instructing Methods for Using Personal-Efficacy and Reading Capacious During Covid-19",
    authors:
      "V. PremaLatha, E. Sreedevi, S. Sivakumar, S.R. Nayak, A.K. Bhoi, U. Ghosh",
    conference: "Advances in Communication, Devices and Networking (ICCDN)",
    volume: "902",
    pages: "223–232",
    year: 2022,
    type: "Springer LNEE",
    category: "conference",
  },
  {
    id: 9,
    title: "Reliable Biometric Authentication with Privacy Protection",
    authors: "S.B. Sharma, I. Dhall, S.R. Nayak, P. Chatterjee",
    conference: "Advances in Communication, Devices and Networking (ICCDN)",
    volume: "902",
    pages: "233–249",
    year: 2022,
    type: "Springer LNEE",
    category: "conference",
  },
  {
    id: 10,
    title:
      "Segmentation and Classification of Skin Cancer Using K-means Clustering and EfficientNetB0 Model",
    authors: "V. Anand, S. Gupta, D. Koundal, S.R. Nayak, J. Shafi, A.K. Bhoi",
    conference: "Advances in Communication, Devices and Networking (ICCDN)",
    volume: "902",
    pages: "471–481",
    year: 2022,
    type: "Springer LNEE",
    category: "conference",
  },
  {
    id: 11,
    title: "Big Data in Education: Present and Futures",
    authors: "J. Nayak, H. Swapnarekha, A.R. Routray, S.R. Nayak, H.S. Behera",
    conference: "Computational Intelligence in Data Mining (Smart Innovation, Systems and Technologies)",
    volume: "281",
    pages: "",
    year: 2022,
    type: "Springer",
    category: "conference",
  },
  {
    id: 12,
    title: "Generation of Interactive Fractals Using Generalized IFS",
    authors: "S.K. Das, J. Mishra, S.R. Nayak",
    conference:
      "Advances in Intelligent Computing and Communication (Lecture Notes in Networks and Systems)",
    volume: "430",
    pages: "Chapter 57",
    year: 2022,
    type: "Springer",
    category: "conference",
  },
  {
    id: 13,
    title: "Lung Cancer Detection using Ensemble of Machine Learning Models",
    authors: "B. Jehangir, S.R. Nayak, S. Shandilya",
    conference: "IEEE International Confluence (CONFUENCE)",
    volume: "",
    pages: "",
    year: 2022,
    type: "IEEE",
    category: "conference",
  },
  {
    id: 14,
    title:
      "GLCM Based LGBM classification for COVID-19 Analysis using Chest X-ray Images",
    authors: "B. Jehangir, S.R. Nayak",
    conference: "IEEE International Confluence (CONFUENCE)",
    volume: "",
    pages: "",
    year: 2022,
    type: "IEEE",
    category: "conference",
  },
  {
    id: 15,
    title: "Face Recognition based Automated Recognition System",
    authors: "A. Sethy, A.K. Rout, S.R. Nayak",
    conference: "IEEE International Confluence (CONFUENCE)",
    volume: "",
    pages: "",
    year: 2022,
    type: "IEEE",
    category: "conference",
  },
  {
    id: 16,
    title:
      "Antimagic Labelling and Square Difference Labeling for Trees and Complete Bipartite Graph",
    authors:
      "S. Sivakumar, S. Vidyanandini, E. Sreedevi, S.R. Nayak",
    conference: "Cognitive Informatics and Soft Computing (CISC 2021)",
    volume: "365",
    pages: "345–354",
    year: 2021,
    type: "Springer LNEE",
    category: "conference",
  },
  {
    id: 17,
    title: "Edge Irregularity Strength exists in the Anti-Theft Network",
    authors:
      "S. Sivakumar, S. Vidyanandini, E. Sreedevi, S.R. Nayak, A.K. Bhoi",
    conference: "Cognitive Informatics and Soft Computing (CISC 2021)",
    volume: "365",
    pages: "355–361",
    year: 2021,
    type: "Springer LNEE",
    category: "conference",
  },
  {
    id: 18,
    title:
      "Prediction of Currency exchange rate: Performance analysis using ANN-GA and ANN-PSO",
    authors:
      "Muskaan, P.K. Sarangi, S. Singh, S.R. Nayak, A.K. Bhoi",
    conference: "Cognitive Informatics and Soft Computing (CISC 2021)",
    volume: "365",
    pages: "363–365",
    year: 2021,
    type: "Springer LNEE",
    category: "conference",
  },
  {
    id: 19,
    title: "Gurmukhi Numerals Recognition using ANN",
    authors:
      "P.K. Sarangi, A.K. Sahoo, G. Kaur, S.R. Nayak, A.K. Bhoi",
    conference: "Cognitive Informatics and Soft Computing (CISC 2021)",
    volume: "365",
    pages: "377–386",
    year: 2021,
    type: "Springer LNEE",
    category: "conference",
  },
  {
    id: 20,
    title:
      "A Review on Internet of Things in Healthcare Applications",
    authors:
      "A. Kislay, P. Singh, A. Shankar, S.R. Nayak, A.K. Bhoi",
    conference: "Cognitive Informatics and Soft Computing (CISC 2021)",
    volume: "365",
    pages: "387–394",
    year: 2021,
    type: "Springer LNEE",
    category: "conference",
  },
  {
    id: 21,
    title:
      "Vehicle Number Plate Detection: An Edge based Approach",
    authors:
      "K.K. Jena, S.R. Nayak, S. Mishra, S. Mishra",
    conference: "International Conference on Advanced Computing and Intelligent Engineering (ICACIE-2019)",
    volume: "1198",
    pages: "24–34",
    year: 2021,
    type: "Springer",
    category: "conference",
  },
  {
    id: 22,
    title:
      "A Hybrid Based Ensemble Learning Model and DNN for Automated Diagnosis of Brain Tumor from MRI Images",
    authors: "B. Jehangir, S.R. Nayak",
    conference: "International Conference on Innovation in Electrical Power Engineering, Communication, and Computing Technology (IEPCCT-2021)",
    volume: "814",
    pages: "309–321",
    year: 2021,
    type: "Springer",
    category: "conference",
  },
  {
    id: 23,
    title: "Analysis of Lung Cancer by using Deep Neural Network",
    authors: "S. Shandilya, S.R. Nayak",
    conference: "International Conference on Innovation in Electrical Power Engineering, Communication, and Computing Technology (IEPCCT-2021)",
    volume: "814",
    pages: "427–436",
    year: 2021,
    type: "Springer",
    category: "conference",
  },
  {
    id: 24,
    title:
      "Recent Advances on Mammogram Imaging for Breast Cancer Analysis: A Technological Review",
    authors: "L. Maan, S.R. Nayak",
    conference: "CIPR-2021",
    volume: "1349",
    pages: "539–549",
    year: 2021,
    type: "Springer",
    category: "conference",
  },
  {
    id: 25,
    title:
      "A Deep Convolutional Neural Network Based Approach for Handwritten Recognition System",
    authors: "A. Sethy, P.K. Patra, S.R. Nayak",
    conference: "CIPR-2021",
    volume: "1349",
    pages: "607–617",
    year: 2021,
    type: "Springer",
    category: "conference",
  },
  {
    id: 26,
    title:
      "Recognition of Isolated Handwritten Gurumukhi Numerals Using Hopfield Neural Network",
    authors: "P. Sarangi, A.K. Sahoo, S.R. Nayak",
    conference: "CIPR-2021",
    volume: "1349",
    pages: "597–605",
    year: 2021,
    type: "Springer",
    category: "conference",
  },
  {
    id: 27,
    title:
      "Usance of Industrial 4.0 Technique to Overcome the Pandemic Situation of COVID-19",
    authors: "V. Bhardwaj, P. Agarwal, M.S. Sisodiya, V. Singh, S.R. Nayak",
    conference: "IOP Conference Series: Material Science and Engineering",
    volume: "1017(1)",
    pages: "012029",
    year: 2021,
    type: "IOP",
    category: "conference",
  },
  {
    id: 28,
    title:
      "An Improved Kernel Density Estimation with Adaptive Bandwidth Selection for Edge Detection",
    authors: "M. Muthukumaran, H. Singh, S.R. Nayak",
    conference: "IEEE International Conference on Intelligent Communication Technologies and Virtual Mobile Networks (ICICV-2021)",
    volume: "",
    pages: "",
    year: 2021,
    type: "IEEE",
    category: "conference",
  },
  {
    id: 29,
    title:
      "A Comparative Study of Deep Learning Models in Text Classification",
    authors: "J. Kolluri, S. Razia, S.R. Nayak",
    conference: "International Conference on Artificial Intelligence in Manufacturing & Renewable Energy (ICAIMRE-2019)",
    volume: "",
    pages: "",
    year: 2019,
    type: "Elsevier SSRN",
    category: "conference",
  },
  {
    id: 30,
    title:
      "Region Grow Using Fuzzy Automated Seed Selection for Weld Defect Segmentation in X-Radiography Image",
    authors: "M. Marveal, S.R. Nayak",
    conference: "International Conference on Artificial Intelligence in Manufacturing & Renewable Energy (ICAIMRE-2019)",
    volume: "",
    pages: "",
    year: 2019,
    type: "Elsevier SSRN",
    category: "conference",
  },
  {
    id: 31,
    title:
      "A Comparative Study and New Classification Algorithm Using NASA MDP Dataset for Software Defect Detection",
    authors: "E. Sreedevi, V. Premlata, S. Sivakumar, S.R. Nayak",
    conference: "IEEE International Conference on Intelligent Sustainable Systems (ICISS 2019)",
    volume: "",
    pages: "312–317",
    year: 2019,
    type: "IEEE",
    category: "conference",
  },
  {
    id: 32,
    title:
      "Optimizing Performance of Text Searching Using CPU and GPUs",
    authors: "M. Musthafa Baig, S. Sivakumar, S.R. Nayak",
    conference: "International Conference on Computing Analytics and Networking (ICCAN-2019)",
    volume: "1119",
    pages: "141–150",
    year: 2018,
    type: "Springer",
    category: "conference",
  },
  {
    id: 33,
    title:
      "Symmetric Axis Based Off-line Odia Handwritten Character and Numeral Recognition",
    authors: "A. Sethy, P.K. Patra, S.R. Nayak, P.M. Jena",
    conference: "IEEE International Conference on Computational Intelligence and Networks (CINE 2017)",
    volume: "",
    pages: "83–87",
    year: 2017,
    type: "IEEE",
    category: "conference",
  },
  {
    id: 34,
    title:
      "An Improved Algorithm to Estimate the Fractal Dimension of Gray Scale Image",
    authors: "S.R. Nayak, J. Mishra, R. Padhy",
    conference: "IEEE International Conference on Signal Processing, Communication, Power and Embedded System (SCOPES-2016)",
    volume: "",
    pages: "1109–1114",
    year: 2016,
    type: "IEEE",
    category: "conference",
  },
  {
    id: 35,
    title: "Analysing Fractal Dimension of Color Images",
    authors: "S.R. Nayak, A. Ranganath, J. Mishra",
    conference: "IEEE International Conference on Computational Intelligence and Networks (CINE 2015)",
    volume: "",
    pages: "156–159",
    year: 2015,
    type: "IEEE",
    category: "conference",
  },
];
export const books = [
  {
    id: 1,
    title: "Intelligent Fractal Based Image Analysis: Applications in Pattern Recognition and Machine Vision",
    authors: "S.R. Nayak, J. Nayak, K. Muhammad, Y. Karaca",
    publisher: "Elsevier",
    year: 2024,
    isbn: "9780443184697",
    category: "book",
  },
  {
    id: 2,
    title: "Deep Learning for Sustainable Agriculture",
    authors: "R.C. Poonia, V. Singh, and S.R. Nayak",
    publisher: "Elsevier",
    year: 2022,
    isbn: "9780323852142",
    category: "book",
  },
  {
    id: 3,
    title: "Smart Sensor Networks Using AI for Industry 4.0: Applications and New Opportunities",
    authors: "S.R. Nayak, B.R. Sahoo, M. Muthukumaran, J. Mishra",
    publisher: "CRC Press (Taylor & Francis)",
    year: 2021,
    isbn: "9781003145028",
    category: "book",
  },
  {
    id: 4,
    title: "Machine Vision Inspection Systems: Machine Learning-Based Approaches",
    authors: "M. Muthukumaran, S.R. Nayak, S.N. Panda, P.K. Pattnaik",
    publisher: "Wiley-Scrivener Publishing",
    year: 2021,
    isbn: "9781119786092",
    category: "book",
  },
  {
    id: 5,
    title: "Machine Vision Inspection Systems: An Image Processing Approach",
    authors: "M. Muthukumaran, S.R. Nayak, S.N. Panda, P.K. Pattnaik, N. Muangnak",
    publisher: "Wiley-Scrivener Publishing",
    year: 2020,
    isbn: "9781119681809",
    category: "book",
  },
  {
    id: 6,
    title: "Examining Fractal Image Processing and Analysis",
    authors: "S.R. Nayak, J. Mishra",
    publisher: "IGI Global, Advances in Computational Intelligence and Robotics (ACIR)",
    year: 2019,
    isbn: "9781799800668",
    category: "book",
  },
  {
    id: 7,
    title: "Pioneering Autonomous Technology: A Deep Dive Into Hyper Automation",
    authors: "S.R. Nayak, K. Swain, R.C. Poonia, P.K. Pattnaik",
    publisher: "Elsevier",
    year: 2024,
    isbn: "Contract Signed (on-going)",
    category: "book",
  },
  {
    id: 8,
    title:
      "Genome Mapping and Advancements in Deep Learning Approaches: Computation and Analysis in Medical Applications",
    authors: "S.R. Nayak, S.P. Singh, J. Singh, P. Singh, M. Diwakar, D. Garg",
    publisher: "CRC Press (Taylor & Francis)",
    year: 2024,
    isbn: "Contract Signed (on-going)",
    category: "book",
  },
]
export const bookChapters = [
  {
    id: 1,
    title: "AI enhanced healthcare: Opportunities, challenges, ethical considerations, and future risk",
    authors: "S. Gupta, S. Mohanty, D. K. Behera, S.R. Nayak",
    publisher: "Responsible and Explainable Artificial Intelligence in Healthcare",
    pages: "127–153",
    year: 2025,
    type: "Elsevier",
    category: "chapter",
  },
  {
    id: 2,
    title: "The Impact of Machine Learning on Chronic Kidney Disease: Analysis and Insights",
    authors: "K. P. Swain, R. K. Nayak, A. Swain, and S. R. Nayak",
    publisher: "Healthcare Industry Assessment: Analyzing Risks, Security, and Reliability",
    pages: "Vol. 11, 121–148",
    year: 2024,
    type: "Springer",
    category: "chapter",
  },
  {
    id: 3,
    title: "Integrative Data Analysis and Automated Deep Learning Techniques for Ovary Detection",
    authors: "S. Acharya, D. Ghosh, H. Swapnarekha, M. Mishra, S.R. Nayak",
    publisher: "Computational Intelligence in Cancer Diagnosis: Progress and Challenges",
    pages: "Chapter 3, 43–65",
    year: 2023,
    type: "Elsevier",
    category: "chapter",
  },
  {
    id: 4,
    title: "Quantitative Assessment of Fetal Wellbeing Through CTG Recordings",
    authors: "S. Sharma, A. Gupta, S.R. Nayak",
    publisher: "Connected e-Health: Integrated IoT and Cloud Computing",
    pages: "Chapter 13",
    year: 2022,
    type: "Springer",
    category: "chapter",
  },
  {
    id: 5,
    title: "A New Extended Differential Box Counting Method by Adopting Unequal Partitioning of Grid for Estimation of Fractal Dimension of Digital Images",
    authors: "S.R. Nayak, R. Padhy, J. Mishra",
    publisher: "Computational Signal Processing and Analysis (LNEE Book Series)",
    pages: "Vol. 490, 45–57",
    year: 2018,
    type: "Springer",
    category: "chapter",
  },
  {
    id: 6,
    title: "Fractal Dimension of Gray Scale Images",
    authors: "S.R. Nayak, J. Mishra",
    publisher: "Progress in Computing, Analytics and Networking (AISC Book Series)",
    pages: "Vol. 710, 225–234",
    year: 2018,
    type: "Springer",
    category: "chapter",
  },
  {
    id: 7,
    title: "Analysis of Medical Images Using Fractal Geometry",
    authors: "S.R. Nayak, J. Mishra",
    publisher: "Histopathological Image Analysis in Medical Decision Making",
    pages: "181–201",
    year: 2018,
    type: "IGI Global",
    category: "chapter",
  },
  {
    id: 8,
    title: "Parallel Computation of a MMDBM Algorithm on GPU Mining with Big Data",
    authors: "S. Sivakumar, S.R. Nayak, S. Sundar, S. Vidyanandini",
    publisher: "Cloud Computing for Geospatial Big Data Analytics: Intelligent Edge, Fog and Mist Computing (Studies in Big Data)",
    pages: "Vol. 49, Chapter 6, 137–153",
    year: 2019,
    type: "Springer",
    category: "chapter",
  },
  {
    id: 9,
    title: "A New and Secure Intrusion Detecting System for Detection of Anomalies Within Big Data",
    authors: "A.S.A.L.G. Gupta, G. Syam Prasad, S.R. Nayak",
    publisher: "Cloud Computing for Geospatial Big Data Analytics: Intelligent Edge, Fog and Mist Computing (Studies in Big Data)",
    pages: "Vol. 49, Chapter 8, 177–188",
    year: 2019,
    type: "Springer",
    category: "chapter",
  },
  {
    id: 10,
    title: "Bio-Medical Image Processing: Medical Image Analysis for Malaria With Deep Learning",
    authors: "R. Lenka, K. Dutta, A. Khandual, S.R. Nayak",
    publisher: "Examining Fractal Image Processing and Analysis (Advances in Computational Intelligence and Robotics)",
    pages: "Chapter 7",
    year: 2019,
    type: "IGI Global",
    category: "chapter",
  },
  {
    id: 11,
    title: "Image Enhancement: Application of Dehazing and Color Correction for Enhancement of Night Time Low Illumination Image",
    authors: "R. Lenka, A. Khandual, K. Dutta, S.R. Nayak",
    publisher: "Examining Fractal Image Processing and Analysis (Advances in Computational Intelligence and Robotics)",
    pages: "Chapter 11",
    year: 2019,
    type: "IGI Global",
    category: "chapter",
  },
  {
    id: 12,
    title: "Offline Handwritten Numeral Recognition Using Convolution Neural Network",
    authors: "A. Sethy, P.K. Patra, S.R. Nayak",
    publisher: "Machine Vision Inspection Systems: Image Processing, Methodologies and Applications",
    pages: "Vol. 1, Chapter 9, 197–212",
    year: 2020,
    type: "Wiley",
    category: "chapter",
  },
  {
    id: 13,
    title: "Emotional Level Classification and Prediction of Tweets in Twitter",
    authors: "E. Rajesh Kumar, K.V.S.N. Rama Rao, S.R. Nayak",
    publisher: "Emotion and Information Processing: A Particle Approach",
    pages: "Chapter 10",
    year: 2020,
    type: "Springer",
    category: "chapter",
  },
  {
    id: 14,
    title: "Machine Learning Based Virus Type Classification Using Transmission Electron Microscopy Virus Images",
    authors: "K.K. Jena, S.K. Bhoi, S.R. Nayak, C. Mallick",
    publisher: "Machine Vision Inspection Systems: Machine Learning-Based Approaches",
    pages: "Vol. 2",
    year: 2021,
    type: "Wiley",
    category: "chapter",
  },
  {
    id: 15,
    title: "Surface Defect Detection Using SVM Based Machine Vision System with Optimized Feature",
    authors: "A.K. Patel, V.N. Mandhalab, D.K. Angurajb, S.R. Nayak",
    publisher: "Machine Vision Inspection Systems: Machine Learning-Based Approaches",
    pages: "Vol. 2",
    year: 2021,
    type: "Wiley",
    category: "chapter",
  },
  {
    id: 16,
    title: "Optimization of Wireless Sensor Networks Using Bio-Inspired Algorithm",
    authors: "A. Swain, K.P. Swain, G. Palai, and S.R. Nayak",
    publisher: "Smart Sensor Network Using AI for Industry 4.0",
    pages: "DOI:10.1201/9781003145028",
    year: 2021,
    type: "CRC Press",
    category: "chapter",
  },
  {
    id: 17,
    title: "Prediction of Paddy Cultivation Using Deep Learning on Land Cover Variation for Sustainable Agriculture",
    authors: "D.A. Meedeniya, I. Mahakalanda, D.S. Lenadora, I. Perera, S.G.S. Hewawalpita, C. Abeysinghe, S.R. Nayak",
    publisher: "Elsevier",
    pages: "",
    year: 2022,
    type: "Elsevier",
    category: "chapter",
  },
  {
    id: 18,
    title: "Integrative Data Analysis and Automated Deep Learning Technique for Ovary Cancer Detection",
    authors: "S. Acharya, D. Ghosh, S.R. Hanumanthu, M. Mishra, S.R. Nayak",
    publisher: "Computational Intelligence in Cancer Diagnosis",
    pages: "",
    year: 2023,
    type: "Elsevier",
    category: "chapter",
  },
];
export const patents = [
  {
    id: 1,
    title: "Device for Segregating Objects in Limited Illumination",
    inventors: "S. R. Nayak. et al.",
    patentNo: "201911041599",
    grantedNo: "354455",
    year: 2020,
    status: "Granted",
    type: "Indian Utility",
    category: "patent",
  },
  {
    id: 2,
    title: "Device for Surface Roughness Measurement of an Object",
    inventors: "S. R. Nayak. et al.",
    patentNo: "201911043717",
    grantedNo: "366328",
    year: 2021,
    status: "Granted",
    type: "Indian Utility",
    category: "patent",
  },
  {
    id: 3,
    title: "Machine Learning Based Hand Sanitizer making and Dispensing Machine",
    inventors: "S. R. Nayak. et al.",
    patentNo: "2021100049",
    grantedNo: "2021100049",
    year: 2021,
    status: "Granted",
    type: "Australia Design",
    category: "patent",
  },
  {
    id: 4,
    title: "Machine Learning Based Water Purifier and Dispenser",
    inventors: "S. R. Nayak. et al.",
    patentNo: "2021100437",
    grantedNo: "2021100437",
    year: 2021,
    status: "Granted",
    type: "Australia Design",
    category: "patent",
  },
  {
    id: 5,
    title: "Helmet (Smart Helmet)",
    inventors: "S. R. Nayak. et al.",
    patentNo: "353451-001",
    grantedNo: "353451-001",
    year: 2021,
    status: "Granted",
    type: "Indian Design",
    category: "patent",
  },
  {
    id: 6,
    title: "Micro-Channel Heat Exchange for Cooling of Electronic Chip",
    inventors: "S. R. Nayak. et al.",
    patentNo: "356591-001",
    grantedNo: "356591-001",
    year: 2022,
    status: "Granted",
    type: "Indian Design",
    category: "patent",
  },
  {
    id: 7,
    title: "Biometric Attendance Device with Touch-Free Body Temperature Screening",
    inventors: "S. R. Nayak. et al.",
    patentNo: "360414-001",
    grantedNo: "360414-001",
    year: 2022,
    status: "Granted",
    type: "Indian Design",
    category: "patent",
  },
  {
    id: 8,
    title: "Artificial Intelligence Based Skin Cancer Inspection Device",
    inventors: "S. R. Nayak. et al.",
    patentNo: "6293058",
    grantedNo: "6293058",
    year: 2023,
    status: "Granted",
    type: "UK Design",
    category: "patent",
  },
  {
    id: 9,
    title: "Wearable Device for Automatic Stress Monitoring",
    inventors: "S. R. Nayak. et al.",
    patentNo: "202111042735",
    grantedNo: "",
    year: 2021,
    status: "Published",
    type: "Indian",
    category: "patent",
  },
  {
    id: 10,
    title: "Optical Lock through Visible Light Communication for Electronic Device",
    inventors: "S. R. Nayak. et al.",
    patentNo: "202111022796",
    grantedNo: "",
    year: 2021,
    status: "Published",
    type: "Indian",
    category: "patent",
  },
  {
    id: 11,
    title: "Multipurpose Footwear",
    inventors: "S. R. Nayak. et al.",
    patentNo: "202111011180",
    grantedNo: "",
    year: 2021,
    status: "Published",
    type: "Indian",
    category: "patent",
  },
  {
    id: 12,
    title: "Safety System for Preventing Motorcycle Accidents due to Loose Garments",
    inventors: "S. R. Nayak. et al.",
    patentNo: "202431093604",
    grantedNo: "",
    year: 2024,
    status: "Published",
    type: "Indian",
    category: "patent",
  },
  {
    id: 13,
    title: "AquaVision: Computer Vision-Based DrainWater Leakage Detection System",
    inventors: "S. R. Nayak. et al.",
    patentNo: "202431083103",
    grantedNo: "",
    year: 2024,
    status: "Published",
    type: "Indian",
    category: "patent",
  },
  {
    id: 14,
    title: "Customer Movement-Based Product Visibility Optimization System for Retail Spaces",
    inventors: "S. R. Nayak. et al.",
    patentNo: "202431095870",
    grantedNo: "",
    year: 2024,
    status: "Published",
    type: "Indian",
    category: "patent",
  },
  {
    id: 15,
    title: "Real-Time Student Engagement and Comprehension Monitoring System using Computer Vision and Facial Emotion Recognition",
    inventors: "S. R. Nayak. et al.",
    patentNo: "202431099438",
    filingDate: "16/12/2024",
    year: 2024,
    status: "Published",
    type: "Indian",
    category: "patent",
  },

]
export const copyrights = [
  {
    id: 1,
    title: "CALOTRACK : AI-Powered Caloric Intake and Expenditure Management System",
    inventors: "S. R. Nayak. et al.",
    regNo: "L-157195/2024",
    year: 2024,
    status: "Registered",
    type: "Indian",
    category: "copyright",
  },
]
export const allPublications = [
  ...journalPublications,
  ...conferencePublications,
  ...books,
  ...bookChapters,
  ...patents,
  ...copyrights,
]
export const years = [...new Set(allPublications.map((pub) => pub.year))].sort((a, b) => b - a)
export const categories = [
  { value: "all", label: "All Publications" },
  { value: "journal", label: "Journal Articles" },
  { value: "conference", label: "Conference Papers" },
  { value: "book", label: "Books" },
  { value: "chapter", label: "Book Chapters" },
  { value: "patent", label: "Patents" },
  { value: "copyright", label: "Copyrights" },
]

export const skillsData: Skill[] = [
  {
    category: "Machine Learning & AI",
    items: [
      { name: "Machine Learning (supervised, unsupervised, transfer learning)", level: "Advanced" },
      { name: "Deep Learning (CNNs, RNNs, Transformers)", level: "Advanced" },
      { name: "Quantum Machine Learning & Quantum Computing (Qiskit, simulators)", level: "Intro/Intermediate" },
      { name: "Image Processing & Fractal Analysis", level: "Advanced" },
      { name: "Signal & Medical Image Analysis (CT, MRI)", level: "Advanced" },
    ],
  },
  {
    category: "Programming & Frameworks",
    items: [
      { name: "Python (NumPy, Pandas, Scikit-learn)", level: "Expert" },
      { name: "Deep Learning Frameworks: PyTorch, TensorFlow/Keras", level: "Advanced" },
      { name: "Qiskit / Quantum SDKs (simulators)", level: "Intermediate" },
      { name: "IoT / Systems & Deployment", level: "" },
      { name: "IoT device interfacing, sensor integration (IoTM)", level: "Advanced" },
    ],
  },
  {
    category: "Research & Data Analysis",
    items: [
      { name: "Data preprocessing, augmentation, and visualization", level: "Expert" },
      { name: "Statistical analysis & experimental design", level: "Advanced" },
      { name: "Reproducible research (Git, Jupyter, Colab)", level: "Advanced" },
      { name: "Academic writing, grant proposal & FDP development", level: "Expert" },
    ],
  },
  {
    category: "Leadership & Collaboration",
    items: [
      { name: "Project leadership & team mentoring", level: "" },
      { name: "Curriculum & FDP design", level: "" },
      { name: "Presentation & teaching (laboratory & lecture)", level: "" },
      { name: "Collaboration with industry and academic partners", level: "" },
    ],
  },
]
export const ongoingStudents: Student[] = [
  {
    name: "Mrs. Chinmayee Pati",
    regNo: "238107",
    topic: "Dynamic Filtering-Enhanced Lightweight CNN for Automated Detection of Intracranial Hemorrhage in CT Images.",
    batch: "2023 Admission Batch",
    status: "Ongoing",
    university: "KIIT University",
  },
  {
    name: "Mr. Kali Prasanna Swain",
    regNo: "2481120",
    topic: "Multimodal and Explainable Vision-Transformer Frameworks for Real-Time Healthcare Diagnostics and Intelligent Systems.",
    batch: "2024 Admission Batch",
    status: "Ongoing",
    university: "KIIT University",
  },
  {
    name: "Mr. Tarini Prasad Pattanaik",
    regNo: "2481146",
    topic: "Advancing Medical Diagnostics with Explainable Artificial Intelligence: A Multimodal Approach Using Interpretable Deep Learning Techniques.",
    batch: "2024 Admission Batch",
    status: "Ongoing",
    university: "KIIT University",
  },
  {
    name: "Mr. Biswajeeban Das",
    regNo: "2581104",
    topic: "TOPIC to be FINALIZED.",
    batch: "2025 Admission Batch",
    status: "Ongoing",
    university: "KIIT University",
  },
];

export const completedStudents: Student[] = [
  {
    name: "Lovedeep Manna",
    regNo: "-",
    topic: "An Automated Deep-Learning Based Framework for Breast cancer Screening using Momogram Images.",
    batch: "2020-2022 Admission Batch",
    status: "Completed",
    university: "AMITY University",
  },
  {
    name: "Basra Jehangir",
    regNo: "-",
    topic: "Kidney Glomerulus Detection using Deep Neural Network.",
    batch: "2020-2022 Admission Batch",
    status: "Completed",
    university: "AMITY University",
  },
  {
    name: "Harshit Jain",
    regNo: "2450046",
    topic: "Deep Learning–Based COVID-19 Detection: An Empirical Study with Modified CNN on Radiography Images.",
    batch: "2024-2025 Admission Batch",
    status: "Ongoing",
    university: "KIIT University",
  },
];
export const awardsData: AwardData[] = [
  {
    icon: Star,
    title: "MHRD Govt. of India Fellowship",
    description: ["TEQIP-II", "2013-2017"],
  },
  {
    icon: Award,
    title: "Best Paper Award",
    description: ["International Conference"],
  },
  {
    icon: Globe,
    title: "World’s Top 2% Scientist",
    description: ["Stanford University", "2024, 2025"],
  },
  {
    icon: User,
    title: "Best Teacher Award",
    description: ["Odisha Technological Conclave", "2024"],
  },
];
export const ProfessionalcardsData: ProfessionalCardData[] = [
  {
    category: "Associate Editor in Journals",
    items: [
      {
        title: "PLOS One",
        description: "Associate Editor since 2022 (Scopus, Web of Science-SCIE)",
        link: "https://journals.plos.org/plosone/s/editorial-board",
      },
      {
        title: "Journal of Electronic Imaging – SPIE",
        description: "2021–2025 (Scopus, Web of Science-SCIE)",
        link: "https://www.spiedigitallibrary.org/journals/journal-of-electronic-imaging",
      },
      {
        title: "Mathematical Problems in Engineering (MPE) – Hindawi",
        description: "Since 2022 (Scopus, Web of Science-SCI)",
        link: "https://www.hindawi.com/journals/mpe/editors/",
      },
      {
        title: "Applied Computational Intelligence and Soft Computing (ACIS) – Hindawi",
        description: "Since 2021 (Scopus, Web of Science-ESCI)",
        link: "https://www.hindawi.com/journals/acisc/editors/",
      },
      {
        title: "International Journal of Biomedical Imaging (IBI) – Hindawi",
        description: "Since 2022 (Scopus, Web of Science-ESCI)",
        link: "https://www.hindawi.com/journals/ijbi/editors/",
      },
      {
        title: "Journal of Cyber Security Technology – Taylor & Francis",
        description: "Since 2023 (Scopus)",
        link: "https://www.tandfonline.com/journals/tcyb20",
      },
    ],
  },
  {
    category: "Guest Editor in Journals",
    items: [
      {
        title: "Journal of Discrete Mathematical Sciences & Cryptography (JDMSC)",
        description: "Special issue: Advances in Artificial Intelligence for Cyber Security (Taylor & Francis)",
      },
    ],
  },
  {
    category: "Reviewers in Journals",
    items: [
      { title: "IEEE Transactions on Emerging Topics in Computational Intelligence" },
      { title: "IEEE ACCESS" },
      { title: "IEEE Consumer Electronics Magazine" },
      { title: "IEEE Internet of Things Journal" },
      { title: "Expert System with Applications (Elsevier)" },
      { title: "Future Generation Computer Systems (Elsevier)" },
      { title: "Information Science (Elsevier)" },
      { title: "Applied Mathematics and Computation (Elsevier)" },
      { title: "Information Fusion (Elsevier)" },
      { title: "Sustainable Computing: Informatics and Systems (Elsevier)" },
      { title: "Applied Soft Computing (Elsevier)" },
      { title: "BioSystems (Elsevier)" },
      { title: "Computers in Biology and Medicine (Elsevier)" },
      { title: "SN Applied Sciences (Springer)" },
      { title: "International Journal of Information Technology (Springer)" },
      { title: "Artificial Intelligent Review (Springer)" },
      { title: "International Journal of Intelligent Systems (Wiley)" },
      { title: "International Journal of Communication System (Wiley)" },
      { title: "Computational Intelligence (Wiley)" },
      { title: "Expert System (Wiley)" },
      { title: "Computer Methods in Biomechanics & Biomedical Engineering (Taylor & Francis)" },
      { title: "Biomedical Engineering: Imaging & Visualization (Taylor & Francis)" },
      { title: "Journal of Applied Remote Sensing (SPIE)" },
      { title: "International Journal of Computer Vision and Image Processing (IGI Global)" },
      { title: "International Journal of Computer Applications in Technology (Inderscience)" },
      { title: "International Journal of Electronic Business (Inderscience)" },
      { title: "Journal of Intelligent & Fuzzy Systems (IOS Press)" },
    ],
  },
  {
    category: "Participated Events",
    items: [
      { title: "SUSCOM-2024", description: "Sri Balaji College of Engineering & Technology, Jaipur, TARU" },
      { title: "EISC-2024", description: "KIIT University, IEEE" },
      { title: "CIPR-2024", description: "MSCB University, Springer" },
      { title: "CISC-2021", description: "BCET, Balasore, Springer" },
      { title: "ICAMPM-2020", description: "NIT Uttarakhand, IOP Press" },
      { title: "SUSCOM-2020", description: "Amity University, Taylor & Francis" },
      { title: "ICAN-2019", description: "KIIT University, Springer" },
      { title: "ICACIE-2019", description: "RD University, Springer" },
      { title: "AI in Manufacturing & Renewable Energy-2019", description: "GIET, Elsevier SSRN" },
      { title: "ISS-2019", description: "SCADIT, IEEE" },
      { title: "ICAN-2018", description: "KIIT University, Springer" },
      { title: "Nextgen Electronic Technologies: Silicon to Software, 2017", description: "VIT University, Chennai" },
      { title: "Many Faculty Development Programs & National Seminars", description: "2013–2020" },
    ],
  },
  {
    category: "Professional Assignments",
    items: [
      { title: "Session Chair", description: "Multiple international conferences (CIPR, SUSCOM, ICCIDM, etc.) from 2018–2024" },
      { title: "Technical Program Committee Member", description: "ICCIDM-2021, ACCES-2022, etc." },
      { title: "Program Committee Chair", description: "Confluence-2022, Amity University" },
      { title: "International Technical Committee Member", description: "CIPR-2021" },
    ],
  },
  {
    category: "Invited Lectures",
    items: [
      { title: "ERTCSE-2020", description: "Biomedical Image Processing (GMR Institute of Technology)" },
      { title: "DLMLCV-2021", description: "Medical Image Analysis using Deep Learning (GMR Institute of Technology)" },
      { title: "UGC-HRDC, JNTUH", description: "Talk on AI/ML Advances in Medical Imaging" },
      { title: "NIT-Warangal", description: "Talk on AI/ML Advances in Medical Imaging" },
    ],
  },
  {
    category: "Organised Events",
    items: [
      { title: "NSFTDW-2012", description: "Future Trends in Data Warehousing, Vivekananda Institute of Technology" },
      { title: "Loophole Ethical Hacking FDP – 2012", description: "AIESEC IIT Kharagpur at Vivekananda Institute of Technology" },
    ],
  },
  {
    category: "Professional Bodies",
    items: [
      { title: "IEEE Member", description: "Member No. 98465105" },
      { title: "ISTE Life Member", description: "LM140676" },
      { title: "IAENG Member", description: "Member No. 184042 (Hong Kong)" },
      { title: "CSTA Life Member", description: "Member No. 76152832" },
    ],
  },
  {
    category: "Adjunct Professor",
    items: [
      { title: "Chandigarh University, Punjab", description: "2020–2022" },
      { title: "SR University, Warangal", description: "2023–2024" },
    ],
  },
];